### ISSUE TITLE
What will be our contribution workflow to gaia?

### ISSUE THREAD

**Issue by autra** [Phoxygen/sw_fm#12]
So I understand we keep the current tree right (repo forked from Vivien)? We're not starting from gaia master? Wouldn't it be too messy when merging back?

**Comment by autra** [comment]
Will we merge back actually?

**Comment by lcuguen-zz** [comment]
Augustin Trancart notifications@github.com writes:

> Will we merge back actually?

[...]

## what's the point ?

Loïc
