### ISSUE TITLE
measure memory gain on visibilitychange

### ISSUE THREAD

**Issue by autra** [Phoxygen/sw_fm#4]

**Comment by peppsac** [comment]
Depends on https://github.com/Phoxygen/sw_fm/issues/8 and https://github.com/Phoxygen/sw_fm/issues/9

**Comment by autra** [comment]
### Measurement method

`watch -n 1 'adb shell b2g-info'`

and I will record the USS (Unique Set Size) column. All measure will be done with earplug plugged it and airplane mode disable.

### Step1: startup memory footprint

I will record memory footprint from stock fm radio and sw_fm after a cold startup.

Method: 
- start the application
- wait for radio to start
- wait 5 sec
- measure.

### Step2: In-use memory footprint

I will record memory footprint after some use (adding/removing favorites, activating speakers, sliding the frequency bars) while keeping the app in foreground for both versions.

### Step3: Memory liberated when going into background

I will record memory footprint for sw_fm when it goes into background.

For the sake of completeness, I'll also check if stock fm frees some memories when going into background.

### Step4: bonus point: reload time

I'll try to assess how long does it take for the app to go back in background. I'll probably measure the time difference between the 'onvisibilitychange' event and the last 'connected' event received by the clients.

**Comment by autra** [comment]
### Measurement method

```watch -n 1 'adb shell b2g-ps' ```

and I will record VSIZE and RSS column.

### Step1: startup memory footprint

I will record memory footprint from stock fm radio and sw_fm after a cold startup.

### Step2: In-use memory footprint

I will record memory footprint after some use (adding/removing favorites, activating speakers, sliding the frequency bars) while keeping the app in foreground for both versions.

### Step3: Memory liberated when going into background

I will record memory footprint for sw_fm when it goes into background.

For the sake of completeness, I'll also check if stock fm frees some memories when going into background.

### Step4: bonus point: reload time

I'll try to assess how long does it take for the app to go back in background. I'll probably measure the time difference between the 'onvisibilitychange' event and the last 'connected' event received by the clients.

**Comment by autra** [comment]
test

**Comment by autra** [comment]
testnrsta

**Comment by autra** [comment]
### Step1

#### Stock fm app

Without bookmarks:

| measure n° | USS |
| --- | --- |
| 1 | 13.5 |
| 2 | 12.2 |
| 3 | 12.5 |
| 4 | 13.3 |
| 5 | 13.3 |
| AVERAGE | 12.96 |

With 6 bookmarks:

| measure n° | USS |
| --- | --- |
| 1 | 13.1 |
| 2 | 13.8 |
| 3 | 13.5 |
| 4 | 12.4 |
| 5 | 12.8 |
| AVERAGE | 13.12 |

#### SW FM

Without bookmarks:

| measure n° | USS |
| --- | --- |
| 1 | 14.5 |
| 2 | 14.9 |
| 3 | 14.3 |
| 4 | 14.2 |
| 5 | 13.7 |
| AVERAGE | 14.32 |

With 6 bookmarks:

| measure n° | USS |
| --- | --- |
| 1 | 14.7 |
| 2 | 14.9 |
| 3 | 14.9 |
| 4 | 14.5 |
| 5 | 14.8 |
| AVERAGE | 14.76 |

So we have a memory hit when adding this abstraction. It is measurable and costs approximatively  10%.

**Comment by autra** [comment]
### Step 2

Is postpone until I set up a more precise test protocol, because the variation are too big if we don't have clear actions. Moreover, the gc behaviour affects this test. I'm not even sure we want to test this.

**Comment by autra** [comment]
### Step 3

| Measure n° | USS foreground | USS background | USS 5 sec background | USS 15 sec background |
| --- | --- | --- | --- | --- |
| 1 | 13.8 | 16 | 15.2 | 14.2 |
| 2 | 14.6 | 15.9 | 16.1 | 13.8 |
| 3 | 14.4 | 14.6 | 15.9 | 14.1 |
| 4 | 15.4 | 15.8 | 15 | 14 |
| 5 | 14.6 | 15.9 | 16 | 14.5 |
| AVERAGE | 14.56 | 15.64 | 15.64 | 14.12 |

What is really odd is as soon as we go background, the memory rises quite a lot. Then it goes down to a level only slightly inferior at those when the app is in foreground.
